version: '3.4'
services:
  st-rest:
    build:
      context: .
      target: development
    container_name: st-rest-development
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FASTIFY_HOST=$FASTIFY_HOST
      - FASTIFY_PORT=$FASTIFY_PORT
    working_dir: /app
    # user: "node:node"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/init/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
