version: '3.4'
services:
  st-rest:
    build:
      context: .
      target: test
    env_file:
      - .env
    container_name: st-rest-test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FASTIFY_HOST=$FASTIFY_HOST
      - FASTIFY_PORT=$FASTIFY_PORT
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/init/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
